// <auto-generated />
namespace RosCottedge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserRegistrationDate_HouseAvatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRegistrationDate_HouseAvatar));
        
        string IMigrationMetadata.Id
        {
            get { return "201707191530518_UserRegistrationDate_HouseAvatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
